### ISSUE TITLE
Ignores all parameters (CSS/SASS/PostCSS)

### ISSUE THREAD

**Issue by strarsis** [herrstucki/responsive-loader#51]
I am using SASS with PostCSS together with responsive-loader in a webpack setup.
The `size` parameter is ignored, always the original (max) size file used.

Example:
```css
.test {
  background-image: url(../images/background.jpg?size=1600&quality=10);
}
````

[`parsedResourceQuery`](https://github.com/herrstucki/responsive-loader/blob/master/src/index.js#L36) is empty for the files referenced from within the SCSS files.
